name: Slack alert for dev branch

on:
  push:
    branches:
      - dev
      - feature/*

  pull_request:
    branches:
      - dev
      - feature/*
      
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

     
